import 'dotenv/config'
const env = {
  DATABASE_NAME: process.env.DATABASE_NAME,
  DATABASE_USERNAME: process.env.DATABASE_USERNAME,
  DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
  DATABASE_CONNECTION_STRING: process.env.DATABASE_CONNECTION_STRING,
  PRODUCTION_PORT: process.env.PRODUCTION_PORT,
  PRODUCTION_HOST: process.env.PRODUCTION_HOST,
  LOCAL_HOST: process.env.LOCAL_HOST,
  LOCAL_PORT: process.env.LOCAL_PORT,
  BUILD_MODE: process.env.BUILD_MODE,
  BREVO_EMAIL_NAME: process.env.BREVO_EMAIL_NAME,
  BREVO_EMAIL_ADDRESS: process.env.BREVO_EMAIL_ADDRESS,
  BREVO_API_KEY: process.env.BREVO_API_KEY,

  JWT_ACCESS_TOKEN_SECRET_KEY: process.env.JWT_ACCESS_TOKEN_SECRET_KEY,
  JWT_ACCESS_TOKEN_TIMELIFE: process.env.JWT_ACCESS_TOKEN_TIMELIFE,
  JWT_REFRESH_TOKEN_SECRET_KEY: process.env.JWT_REFRESH_TOKEN_SECRET_KEY,
  JWT_REFRESH_TOKEN_TIMELIFE: process.env.JWT_REFRESH_TOKEN_TIMELIFE,

  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET
}

export { env }
